service: ses-event
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  lambdaHashingVersion: 20201221

functions:
  sesEvent:
    handler: handler.sesEvent
    memorySize: 128
    timeout: 20