service: image
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  region: ap-northeast-1
  lambdaHashingVersion: 20201221

functions:
  resize:
    handler: handler.resizeImage
    memorySize: 512
    timeout: 30
    events:
      - s3:
          bucket: kyo-demo
          event: s3:ObjectCreated:*
