service: image
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  lambdaHashingVersion: 20201221

functions:
  resize:
    handler: handler.resizeImage
    memorySize: 512
    timeout: 30
