service: hello-world
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 20
    events:
      - schedule: cron(0 12 * * ? *)