service: serverless-simple-http-endpoint
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  region: ap-northeast-1
  lambdaHashingVersion: 20201221

functions:
  greeting:
    handler: handler.endpoint
    memorySize: 128
    timeout: 20
    events:
      - httpApi:
          path: /message
          method: get