service: kg
frameworkVersion: '2'

provider:
  name: google
  runtime: nodejs14
  region: asia-east2
  project: fifth-audio-321904
  credentials: C:/Users/kyo.cheng15/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions
functions:
  search:
    handler: kgSearch
    memorySize: 128
    timeout: 20s
    events:
      - http: slack
