service: encrypt
frameworkVersion: '2'

provider:
  name: google
  runtime: php74
  region: asia-east2
  project: xxx
  credentials: C:/Users/kyo.cheng15/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions
functions:
  code:
    handler: get_encrypt_code
    memorySize: 128
    timeout: 20s
    events:
      - http: encrypt-code