service: state-machine
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  region: ap-northeast-1
  stage: dev
  lambdaHashingVersion: 20201221
  environment:
    awsAccount: xxx
    STEP_FUNCTION_ARN: "arn:aws:states:${self:provider.region}:${self:provider.environment.awsAccount}:stateMachine:TechDayStepFunctionsStateMachine-xxx"
    FIRST_FUNCTION_ARN: "arn:aws:lambda:${self:provider.region}:${self:provider.environment.awsAccount}:function:${self:service}-${self:provider.stage}-stateMachineFirstStep"
    CHOICE_FUNCTION_ARN: "arn:aws:lambda:${self:provider.region}:${self:provider.environment.awsAccount}:function:${self:service}-${self:provider.stage}-stateMachineChoiceStep"
    END_FUNCTION_ARN: "arn:aws:lambda:${self:provider.region}:${self:provider.environment.awsAccount}:function:${self:service}-${self:provider.stage}-stateMachineEndStep"
functions:
  startStateMachine:
    handler: handler.startExecution
    memorySize: 128
    timeout: 20
  stateMachineFirstStep:
    handler: handler.firstStep
    memorySize: 128
    timeout: 20
  stateMachineChoiceStep:
    handler: handler.choiceStep
    memorySize: 128
    timeout: 20
  stateMachineEndStep:
    handler: handler.endStep
    memorySize: 128
    timeout: 20

# define the state machine
stepFunctions:
  stateMachines:
    TechDay:     
      definition:
        StartAt: Start-Func
        States:
          Start-Func:
            Type: Task
            Resource: "${self:provider.environment.FIRST_FUNCTION_ARN}"
            Next: Next-Func
          Next-Func:
            Type: Task
            Resource: "${self:provider.environment.CHOICE_FUNCTION_ARN}"
            Next: Choices-Func
          Choices-Func:
            Type: Choice
            Choices:
            - Variable: "$.randomNumber"
              NumericEquals: 0
              Next: Start-Func
            - Variable: "$.randomNumber"
              NumericEquals: 1
              Next: End-Func
          End-Func:
            Type: Task
            Resource: "${self:provider.environment.END_FUNCTION_ARN}"
            End: True

package:
  exclude:
    - node_modules/**
    - .serverless/**

plugins:
  - serverless-step-functions
